### ISSUE TITLE
postRS: Record line invalid

### ISSUE THREAD

**Issue by stantoxt** [anrip/ArDNSPod#10]
admin@CntR6300V2:/jffs/scripts# ./ddnspod.sh
Linux
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
hostIP: 192.168.1.6 192.168.6.1
lastIP:
postRS: Record line invalid

我出现这写问题，我的路由器的上级路由器链接外网

**Comment by ProfFan** [comment]
你没有 wget

**Comment by anrip** [comment]
可以更换curl或者其他的可以请求https的命令

**Comment by stantoxt** [comment]
不好意思，前段时间我忙别的了，回复晚了，这应该都是有的，想问下大神 @ProfFan @anrip 为什么阿里云的产品没有类似脚本的写法，是因为他的加密方法在脚本里面很难实现，还是安全性考虑，或者是别的原因

**Comment by ProfFan** [comment]
Closed. See https://github.com/anrip/ArDNSPod/issues/11

**Comment by ProfFan** [comment]
@stantoxt there is a python library called dns-lexicon

**Comment by stantoxt** [comment]
已经看过了这里结帖问题，感谢帮助啊！dns-lexicon 继承了这么多个，咋就没有阿里云，希望 @ProfFan  @anrip 两位大神 ，搞阿里云的，否则还是要用官方其他版本的sdk，来进行操作。
