### ISSUE TITLE
line 96: command: not found

### ISSUE THREAD

**Issue by DDior** [anrip/ArDNSPod#11]
on Netgear R7000 & Merlin 380.57_X6.5

error message are below:

Linux                                                                         
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
hostIP: xxx.xxx.xxx.xxx
lastIP:                          
postRS:xxx.xxx.xxx.xxx

**Comment by ProfFan** [comment]
Please check whether you have curl or wget installed.

**Comment by anrip** [comment]
may be have not the dirname commond, you can input the full path instead of it

**Comment by DDior** [comment]
@ProfFan thx for your response.  i checked and confirm that wget and curl have been installed correctly. :)

**Comment by DDior** [comment]
@anrip i try to run dirname command from ssh, and get below prompts:

>SUSWRT-Merlin R7000_3.0.0.4 Sun Jan 31 12:52:51 UTC 2016
admin@R7000-F2A7:/tmp/home/root# dirname
BusyBox v1.20.2 (2015-12-30 09:41:58 CST) multi-call binary.

>Usage: dirname FILENAME

>Strip non-directory suffix from FILENAME

**Comment by ProfFan** [comment]
You can try "bash -x <this script>" and paste the results here.

**Comment by DDior** [comment]
@ProfFan i run the script on a Router but not Mac...
>SUSWRT-Merlin R7000_3.0.0.4 Sun Jan 31 12:52:51 UTC 2016
admin@R7000-F2A7:/tmp/home/root# bash -x
-sh: bash: not found

**Comment by ProfFan** [comment]
then `sh -x` if you do not have bash

**Comment by anrip** [comment]
OK 我发现你是中国人，把你的脚本贴出来，我们看看96行是什么代码吧。

**Comment by DDior** [comment]
@anrip 若海好。

96行的代码如下：
    DIR=$(dirname -- "$(rreadlink "$0")")

**Comment by anrip** [comment]
应该是没有 rreadlink 
 
 
------------------ 原始邮件 ------------------
发件人: "XuanYuan"; 
发送时间: 2016年11月28日(星期一) 中午11:20
收件人: "anrip/ArDNSPod"; 
抄送: "若海"; "Mention"; 
主题: Re: [anrip/ArDNSPod] line 96: command: not found (#11)

 


@anrip 若海好。
 
96行的代码如下：
 DIR=$(dirname -- "$(rreadlink "$0")")
 
&mdash;

**Comment by ProfFan** [comment]
现在最重要的是要知道你是什么 shell，因为这个 script 我自己在 zsh、bash 和 sh 上都测试过。

**Comment by anrip** [comment]
这个是用来获取当前的脚本路径的，你可以直接修改为自己的脚本路径
 
------------------ 原始邮件 ------------------
发件人: "XuanYuan"<notifications@github.com>;
发送时间: 2016年11月28日(星期一) 中午11:20
收件人: "anrip/ArDNSPod"<ArDNSPod@noreply.github.com>; 
抄送: "若海"<mail@anrip.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [anrip/ArDNSPod] line 96: command: not found (#11)

 

@anrip 若海好。
 
96行的代码如下：
 DIR=$(dirname -- "$(rreadlink "$0")")

**Comment by DDior** [comment]
@ProfFan merlin 固件用的是busybox，不知道应该算是什么 shell，我运行 sh -x 没有任何回显。
@anrip 不好意思，我的脚本是放在 /jffs/scripts/， 请问如何替换语句？

**Comment by DDior** [comment]
@ProfFan 方便给个其他联系方式么？我把sh -x的信息贴出来，里面有IP和token之类的信息，不方便贴在这里。

**Comment by anrip** [comment]
把那个路径直接替换为 /jffs/scripts/，不要动态获取
------------------ 原始邮件 ------------------
发件人: "XuanYuan"<notifications@github.com>
发送时间: 2016年11月29日(星期二) 晚上10:10
收件人: "anrip/ArDNSPod"<ArDNSPod@noreply.github.com>;
抄送: "若海"<mail@anrip.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [anrip/ArDNSPod] line 96: command: not found (#11)



@ProfFan merlin 固&#x4EF6;用的是busybox，不知道应该算是什么 shell，我运行 sh -x 没有任何回显。
 @anrip 不好意思，我的脚本是放在 /jffs/scripts/， 请问如何替换语句？
 
&mdash;

**Comment by DDior** [comment]
@anrip 
不好意思，不大懂 shell 编程，请问该替换哪句？是直接替换96行还是前面的某个变量值？

**Comment by anrip** [comment]
DIR=/jffs/scripts/ 即可

**Comment by ProfFan** [comment]
Assumed closed due to inactivity.
