### ISSUE TITLE
建议获取公网IP使用ip route get 8.8.8.8 | awk '{ print $NF; exit }'命令，毕竟第三方网址不安全可靠性差

### ISSUE THREAD

**Issue by ulpyuxa** [anrip/ArDNSPod#35]
ip route命令获取路由器的公网IP：
ip route get 8.8.8.8 | awk '{ print $NF; exit }'
基本上所有路由器都有ip这个命令，这样就可以不用访问第三方的网址获取公网IP。
第三方网址的问题：
1. 如果第三方的网址加了调用频次那就麻烦大了，
2. 或者第三方的网址挂了也是一样的麻烦

**Comment by ProfFan** [comment]
Please refer to the code

**Comment by anrip** [comment]
这个脚本制作之初衷是最小化依赖shell工具，以最大化兼容linux发行版及嵌入式系统，ip 工具的使用可能会破坏这个想法。我不确定是否所有的设备都会有这个工具。

**Comment by ulpyuxa** [comment]
需要上网的路由器都会集成ip 这个命令，
我测试过华硕自带系统、openwrt、Linux、Mac os都是支持ip命令的
