### ISSUE TITLE
Not support Openwrt any more

### ISSUE THREAD

**Issue by wbchn** [anrip/ArDNSPod#4]
@ProfFan 

After #2 pull, using net device `eth0` and using `update` dns method instead of `ddns` method, and this will failed in which does not have eth0 environment, such as `Openwrt`. 

Because `Openwrt` using `ppp0` for PPPOE, or `eth0.1` as wan net devices, so script will failed when get ip address.

**Comment by ProfFan** [comment]
I am trying to find a better method to detect the active ethernet adaptor. Any idea on this issue? or maybe we can just add a config entry for this.

**Comment by ProfFan** [comment]
@wbchn Just tried a fix, can you test it out on your machine?

**Comment by wbchn** [comment]
@ProfFan It works now.

I have no good idea about exclude private ip list from all ip address list.

One more question: 
`extip=$(ip -o -4 addr list | grep -Ev '\s(docker|lo)' | awk '{print $4}' | cut -d/ -f1 | grep -Ev '(^127....')`
`extip=$(ip -o -4 addr list | grep -Ev '\s(docker|lo)' | awk '{print $4}' | cut -d/ -f1 )` maybe return list of ip address.
How about using `head -n1` cut the first ip as extip?

**Comment by ProfFan** [comment]
Maybe yes, but the thing here I want to implement is actually a kind of priority rule. You can change it and send me a pull request, which makes your idea clearer :)

**Comment by ProfFan** [comment]
@wbchn Could you please help test the revision I just posted on OpenWRT? I **changed the config file format**, which may be breaking.

**Comment by ProfFan** [comment]
Closing due to lack of response.
