### ISSUE TITLE
R7000使用hostIP获取到两个值，导致更新失败，提示postRS: Record line invalid

### ISSUE THREAD

**Issue by jm0477** [anrip/ArDNSPod#6]
确认sh脚本及dns.conf文件 的编码为utf8
手动运行ddnspod.sh 提示
admin@R7000-56A2:/jffs/scripts# ./ddnspod.sh 
Linux
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
./ddnspod.sh: line 96: command: not found
hostIP: 169.254.53.112 123.117.202.xx
lastIP: 
postRS: Record line invalid

目测是由于获取到两个hostIP,第一个好像是个私有ip。 
 不知道如何解决，等待您的回复，谢谢！

**Comment by jm0477** [comment]
我查看了下本地网卡，有一个eth0 是私有ip
eth0       Link encap:Ethernet  HWaddr 9C:D2:1E:A9:25:13  
           inet addr:169.254.53.112  Bcast:169.254.255.255  Mask:255.255.0.0
           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
           RX packets:42221 errors:0 dropped:0 overruns:0 frame:0
           TX packets:44175 errors:0 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:1000 
           RX bytes:27823270 (26.5 MiB)  TX bytes:12340264 (11.7 MiB)
           Interrupt:179 Base address:0x4000 
是由于匹配到了这个网卡吗？
正确的外网ip的名称应该是ppp0

**Comment by jm0477** [comment]
哈哈，解决了， 
把你的正则表达式改了改。
您的原版正则匹配漏掉了169的私有ip段换成下面的就可以忽略169-172了吧，您看下：
line 16:
        extip=$(ip -o -4 addr list | grep -Ev '\s(docker|lo)' | awk '{print $4}' | cut -d/ -f1 | grep -Ev '(^127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$)|(^10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$)|(^169\.1[6-9]{1}[0-9]{0,1}\.[0-9]{1,3}\.[0-9]{1,3}$)|(^169\.2[0-9]{1}[0-9]{0,1}\.[0-9]{1,3}\.[0-9]{1,3}$)|(^169\.3[0-1]{1}[0-9]{0,1}\.[0-9]{1,3}\.[0-9]{1,3}$)|(^192\.168\.[0-9]{1,3}\.[0-9]{1,3}$)')

**Comment by ProfFan** [comment]
这个我们暂时应该不会改的，RFC 1918规定的私有IP段不包括169。您可以自己根据自己情况修改：）

**Comment by jm0477** [comment]
非常感谢！
