### ISSUE TITLE
Openwrt不知道怎么中间无法运行

### ISSUE THREAD

**Issue by Mapaler** [anrip/ArDNSPod#8]
放在路由上运行后wget报错
![image 3](https://cloud.githubusercontent.com/assets/6565860/18256002/1cd2078a-73e2-11e6-9126-a197d962e2d5.png)

我试了有wget，安装bash在bash中运行也是一样的报错
![image 4](https://cloud.githubusercontent.com/assets/6565860/18256553/6783ed3c-73e9-11e6-9b53-f81349322d3b.png)
===================================
后来换成CURL后成功了
![image 5](https://cloud.githubusercontent.com/assets/6565860/18256555/6e272b18-73e9-11e6-9ea5-9889e6ccd41c.png)
![image 6](https://cloud.githubusercontent.com/assets/6565860/18256557/73351dd6-73e9-11e6-8f25-ea86fd19685c.png)
===================================
按网上说的用crontab添加任务，结果找不到怎么编辑，用-e命令进入的是vim，完全不会操作，连退出都不会。
最后用WinSCP修改了/etc/crontab/root才成功了

**Comment by ProfFan** [comment]
crontab记得先设置EDITOR环境变量

**Comment by Mapaler** [comment]
不会用Linux啊，wget用不了是怎么回事

**Comment by ProfFan** [comment]
没有完整的OpenSSL
